modLoader="javafml" #mandatory

loaderVersion="[34, 35, 36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="GPLv3"

[[mods]] #mandatory

modId="anvilclient" #mandatory

version="${file.jarVersion}" #mandatory

displayName="Anvilclient" #mandatory

displayURL="https://github.com/Anvilclient/Anvilclient" #optional

logoFile="anvilclient.png" #optional

credits="" #optional

authors="Amboss_Mann" #optional

description='''
A utility mod for Minecraft
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.anvilclient]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[34, 35, 36,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
    
# Here's another dependency
[[dependencies.anvilclient]]
    modId="minecraft"
    mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[1.16.3, 1.16.4, 1.16.5,)"
    ordering="NONE"
    side="BOTH"